# Generated by Django 4.2.16 on 2024-11-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_payment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
    ]
