# Generated by Django 4.2.16 on 2024-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_remove_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
