# Generated by Django 4.2.16 on 2024-11-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("table_number", models.IntegerField()),
                ("reservation_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("confirmed", "Onaylandı"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
