# Generated by Django 4.2.16 on 2024-11-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.menuitem"
            ),
        ),
    ]
