# Generated by Django 4.2.16 on 2024-11-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("kitchen", "0002_alter_order_menu_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="reservations.reservation",
            ),
        ),
    ]
